language: php

php: ["7.2"]

sudo: false

cache:
    - $HOME/.composer/cache/files

install:
    - travis_retry composer install

script:
    - cp vendor/sensiolabs/security-advisories/validator.php sa_yaml/8/
    - sed -i "s/__DIR__.'/__DIR__.'\/..\/../g" sa_yaml/8/validator.php
    - cp vendor/sensiolabs/security-advisories/validator.php sa_yaml/7/
    - sed -i "s/__DIR__.'/__DIR__.'\/..\/../g" sa_yaml/7/validator.php
    - php sa_yaml/8/validator.php
    - php sa_yaml/7/validator.php

