name: Build on webhook
on: repository_dispatch

jobs:
  build:
    name: Build on webhook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./deploy/
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}